DROP TABLE IF EXISTS `car`;
CREATE TABLE `car` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`price` INT(10) UNSIGNED NOT NULL,
	`year` INT(4) UNSIGNED NOT NULL,
    `make` VARCHAR(100) NOT NULL,
    `model` VARCHAR(100) NOT NULL,
    `mileage` INT(10) UNSIGNED NOT NULL,
    `color` VARCHAR(50) NOT NULL,
    `state` VARCHAR(50) NOT NULL,
    `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARSET=LATIN1;
